runtime: python39

env_variables:
  FLASK_ENV: production
  SECRET_KEY: your-secret-key-here

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

